// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-CIdWnIlsZ1F38hCS0DxnpOSnDnnJwsU',
    appId: '1:299412323226:web:aee5a90a2d20325e78d823',
    messagingSenderId: '299412323226',
    projectId: 'smart-education-007-2cfe0',
    authDomain: 'smart-education-007-2cfe0.firebaseapp.com',
    databaseURL: 'https://smart-education-007-2cfe0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-education-007-2cfe0.firebasestorage.app',
    measurementId: 'G-74FV7WPM3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR93gT0dggfZbhfWi7AG74cwf0tML5wMU',
    appId: '1:299412323226:android:c7bf7684bc80ee4078d823',
    messagingSenderId: '299412323226',
    projectId: 'smart-education-007-2cfe0',
    databaseURL: 'https://smart-education-007-2cfe0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-education-007-2cfe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1zLMESE5XjFAx4DlvzG5m8S-Sot-ybs',
    appId: '1:299412323226:ios:f475f9708fa425fa78d823',
    messagingSenderId: '299412323226',
    projectId: 'smart-education-007-2cfe0',
    databaseURL: 'https://smart-education-007-2cfe0-default-rtdb.firebaseio.com',
    storageBucket: 'smart-education-007-2cfe0.firebasestorage.app',
    iosBundleId: 'com.niter.smartEducationApp.smartEducationApp',
  );
}
